from django.shortcuts import render
from django.conf import settings
import os
from pyswip import Prolog

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status

# PARADIGM: Logic Programming (Inference & Knowledge Representation)
# We initialize the Prolog engine once when the server starts.
prolog = Prolog()
prolog_path = os.path.join(settings.BASE_DIR, '..', 'prolog_engine', 'smart_study_advisor.pl')
prolog.consult(os.path.abspath(prolog_path).replace('\\', '/'))

# PARADIGM: Object-Oriented Programming (System Design)
# Inheriting from APIView encapsulates HTTP methods inside a class structure.
class CourseRecommendationView(APIView):
    
    def post(self, request):
        # PARADIGM: Imperative (Execution Flow)
        # Extract the payload sent by the mobile app
        student_prefs = request.data.get('preferences', {})
        
        level = student_prefs.get('level', 'beginner')
        interests = student_prefs.get('interests', [])
        completed_courses = student_prefs.get('completed_courses', [])

        student_id = "temp_student"

        # Assert dynamic facts for this student
        prolog.assertz(f"level({student_id}, {level})")
        for interest in interests:
            prolog.assertz(f"prefers({student_id}, {interest})")
        for course in completed_courses:
            prolog.assertz(f"completed({student_id}, {course})")

        recommendations = []
        try:
            # Query the Prolog engine for recommendations
            results = list(prolog.query(f"recommend({student_id}, Course)"))
            
            seen_courses = set()
            for res in results:
                course_name = res['Course']
                
                # Check to avoid duplicate course recommendations
                if course_name in seen_courses:
                    continue
                seen_courses.add(course_name)

                # Fetch course difficulty
                diff_results = list(prolog.query(f"course({course_name}, Difficulty)"))
                difficulty = diff_results[0]['Difficulty'] if diff_results else "unknown"

                recommendations.append({
                    "course_name": str(course_name).replace('_', ' ').title(),
                    "difficulty": str(difficulty).capitalize(),
                    "match_reason": "Matches your preferences"
                })
        finally:
            # Retract the facts to clean up the knowledge base
            prolog.retractall(f"level({student_id}, _)")
            prolog.retractall(f"prefers({student_id}, _)")
            prolog.retractall(f"completed({student_id}, _)")

        return Response({
            "status": "success",
            "message": "Recommendations generated by Prolog engine.",
            "recommendations": recommendations
        }, status=status.HTTP_200_OK)
